# Generated by Django 5.2.1 on 2025-05-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficho',
            name='hora',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
