# Generated by Django 5.2.1 on 2025-05-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ficho_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficho',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
