# Generated by Django 5.2.1 on 2025-05-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ficho_hora_validacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficho',
            old_name='fecha_solicitud',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ficho',
            name='hora_validacion',
        ),
        migrations.AlterField(
            model_name='ficho',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='ficho',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
