# Generated by Django 5.2.1 on 2025-05-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_fecha_solicitud_ficho_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficho',
            name='hora_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
