# Generated by Django 5.2.1 on 2025-05-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cupo_nombre_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupo',
            name='nombre_servicio',
            field=models.CharField(choices=[('desayuno', 'Desayuno (6:45 am - 8:30 am)'), ('almuerzo', 'Almuerzo (11:30 am - 1:30 pm)'), ('cena', 'Cena (5:30 pm - 7:30 pm)')], max_length=100, verbose_name='Servicio'),
        ),
    ]
